- name: Install nginx and deploy custom index
  hosts: webservers
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "Hi Jenkins Ansible\n"
